use std::collections::HashMap;

#[derive(Clone)]

pub struct InstrData {
    //printable name
    pub name: String,
    //lengths for this instruction
    pub len: usize,
    //cycles for this instruction
    pub cycles: usize,
}
impl InstrData {
    pub fn new(name: &str, len: usize, cycles: usize) -> Self {
        return InstrData {
            name: name.to_string(),
            len,
            cycles,
        };
    }
}

#[derive(Clone)]

pub struct Instr {
    //hashmap of opcode to instr data
    //TODO: could instead use a vec ordered by opcode for constant lookup
    //ignore above, this should already by constant lookup
    //later note: hashmap is already constant lookup lol? might look neater as a vec tho.
    //look at peachy's crystal emulator
    pub instrs: HashMap<u8, InstrData>,
}

impl Instr {
    pub fn new() -> Self {
        let map = HashMap::from([
            (0x69, InstrData::new("ADC", 2, 2)),
            (0x65, InstrData::new("ADC", 2, 3)),
            (0x75, InstrData::new("ADC", 2, 4)),
            (0x6D, InstrData::new("ADC", 3, 4)),
            (0x7D, InstrData::new("ADC", 3, 4)),
            (0x79, InstrData::new("ADC", 3, 4)),
            (0x61, InstrData::new("ADC", 2, 6)),
            (0x71, InstrData::new("ADC", 2, 5)),
            (0x29, InstrData::new("AND", 2, 2)),
            (0x25, InstrData::new("AND", 2, 3)),
            (0x35, InstrData::new("AND", 2, 4)),
            (0x2D, InstrData::new("AND", 3, 4)),
            (0x3D, InstrData::new("AND", 3, 4)),
            (0x39, InstrData::new("AND", 3, 4)),
            (0x21, InstrData::new("AND", 2, 6)),
            (0x31, InstrData::new("AND", 2, 5)),
            (0x4C, InstrData::new("JMP", 3, 3)),
            (0x6C, InstrData::new("JMP", 3, 5)),
            (0xA2, InstrData::new("LDX", 2, 2)),
            (0xA6, InstrData::new("LDX", 2, 3)),
            (0xB6, InstrData::new("LDX", 2, 4)),
            (0xAE, InstrData::new("LDX", 3, 4)),
            (0xBE, InstrData::new("LDX", 3, 4)),
            (0x86, InstrData::new("STX", 2, 3)),
            (0x96, InstrData::new("STX", 2, 4)),
            (0x8E, InstrData::new("STX", 3, 4)),
            (0x20, InstrData::new("JSR", 3, 6)),
            (0xEA, InstrData::new("NOP", 1, 2)),
            (0x38, InstrData::new("SEC", 1, 2)),
            (0xB0, InstrData::new("BCS", 2, 2)),
            (0x18, InstrData::new("CLC", 1, 2)),
            (0x90, InstrData::new("BCC", 2, 2)),
            (0xA9, InstrData::new("LDA", 2, 2)),
            (0xA5, InstrData::new("LDA", 2, 3)),
            (0xB5, InstrData::new("LDA", 2, 4)),
            (0xAD, InstrData::new("LDA", 3, 4)),
            (0xBD, InstrData::new("LDA", 3, 4)),
            (0xB9, InstrData::new("LDA", 3, 4)),
            (0xA1, InstrData::new("LDA", 2, 6)),
            (0xB1, InstrData::new("LDA", 2, 5)),
            (0xF0, InstrData::new("BEQ", 2, 2)),
            (0xD0, InstrData::new("BNE", 2, 2)),
            (0x85, InstrData::new("STA", 2, 3)),
            (0x95, InstrData::new("STA", 2, 4)),
            (0x8D, InstrData::new("STA", 3, 4)),
            (0x9D, InstrData::new("STA", 3, 5)),
            (0x99, InstrData::new("STA", 3, 5)),
            (0x81, InstrData::new("STA", 2, 6)),
            (0x91, InstrData::new("STA", 2, 6)),
            (0x24, InstrData::new("BIT", 2, 3)),
            (0x2C, InstrData::new("BIT", 3, 4)),
            (0x70, InstrData::new("BVS", 2, 2)),
            (0x50, InstrData::new("BVC", 2, 2)),
            (0x10, InstrData::new("BPL", 2, 2)),
            (0x60, InstrData::new("RTS", 1, 6)),
            (0x00, InstrData::new("BRK", 1, 7)),
            (0x78, InstrData::new("SEI", 1, 2)),
            (0xF8, InstrData::new("SED", 1, 2)),
            (0x08, InstrData::new("PHP", 1, 3)),
            (0x68, InstrData::new("PLA", 1, 4)),
            (0x29, InstrData::new("AND", 2, 2)),
            (0x25, InstrData::new("AND", 2, 3)),
            (0x35, InstrData::new("AND", 2, 4)),
            (0x2D, InstrData::new("AND", 3, 4)),
            (0x3D, InstrData::new("AND", 3, 4)),
            (0x39, InstrData::new("AND", 3, 4)),
            (0x21, InstrData::new("AND", 2, 6)),
            (0x31, InstrData::new("AND", 2, 5)),
            (0xC9, InstrData::new("CMP", 2, 2)),
            (0xC5, InstrData::new("CMP", 2, 3)),
            (0xD5, InstrData::new("CMP", 2, 4)),
            (0xCD, InstrData::new("CMP", 3, 4)),
            (0xDD, InstrData::new("CMP", 3, 4)),
            (0xD9, InstrData::new("CMP", 3, 4)),
            (0xC1, InstrData::new("CMP", 2, 6)),
            (0xD1, InstrData::new("CMP", 2, 5)),
            (0xD8, InstrData::new("CLD", 1, 2)),
            (0x48, InstrData::new("PHA", 1, 3)),
            (0x28, InstrData::new("PLP", 1, 4)),
            (0x30, InstrData::new("BMI", 2, 2)),
            (0x09, InstrData::new("ORA", 2, 2)),
            (0x05, InstrData::new("ORA", 2, 3)),
            (0x15, InstrData::new("ORA", 2, 4)),
            (0x0D, InstrData::new("ORA", 3, 4)),
            (0x1D, InstrData::new("ORA", 3, 4)),
            (0x19, InstrData::new("ORA", 3, 4)),
            (0x01, InstrData::new("ORA", 2, 6)),
            (0x11, InstrData::new("ORA", 2, 5)),
            (0xB8, InstrData::new("CLV", 1, 2)),
            (0x49, InstrData::new("EOR", 2, 2)),
            (0x45, InstrData::new("EOR", 2, 3)),
            (0x55, InstrData::new("EOR", 2, 4)),
            (0x4D, InstrData::new("EOR", 3, 4)),
            (0x5D, InstrData::new("EOR", 3, 4)),
            (0x59, InstrData::new("EOR", 3, 4)),
            (0x41, InstrData::new("EOR", 2, 6)),
            (0x51, InstrData::new("EOR", 2, 5)),
            (0xA0, InstrData::new("LDY", 2, 2)),
            (0xA4, InstrData::new("LDY", 2, 3)),
            (0xB4, InstrData::new("LDY", 2, 4)),
            (0xAC, InstrData::new("LDY", 3, 4)),
            (0xBC, InstrData::new("LDY", 3, 4)),
            (0xE0, InstrData::new("CPX", 2, 2)),
            (0xE4, InstrData::new("CPX", 2, 3)),
            (0xEC, InstrData::new("CPX", 3, 4)),
            (0xC0, InstrData::new("CPY", 2, 2)),
            (0xC4, InstrData::new("CPY", 2, 3)),
            (0xCC, InstrData::new("CPY", 3, 4)),
            (0xE9, InstrData::new("SBC", 2, 2)),
            (0xE5, InstrData::new("SBC", 2, 3)),
            (0xF5, InstrData::new("SBC", 2, 4)),
            (0xED, InstrData::new("SBC", 3, 4)),
            (0xFD, InstrData::new("SBC", 3, 4)),
            (0xF9, InstrData::new("SBC", 3, 4)),
            (0xE1, InstrData::new("SBC", 2, 6)),
            (0xF1, InstrData::new("SBC", 2, 5)),
            (0xE8, InstrData::new("INX", 1, 2)),
            (0xC8, InstrData::new("INY", 1, 2)),
            (0xCA, InstrData::new("DEX", 1, 2)),
            (0x88, InstrData::new("DEY", 1, 2)),
            (0xAA, InstrData::new("TAX", 1, 2)),
            (0xA8, InstrData::new("TAY", 1, 2)),
            (0xBA, InstrData::new("TSX", 1, 2)),
            (0x8A, InstrData::new("TXA", 1, 2)),
            (0x9A, InstrData::new("TXS", 1, 2)),
            (0x98, InstrData::new("TYA", 1, 2)),
            (0x40, InstrData::new("RTI", 1, 6)),
            (0x4A, InstrData::new("LSR", 1, 2)),
            (0x46, InstrData::new("LSR", 2, 5)),
            (0x56, InstrData::new("LSR", 2, 6)),
            (0x4E, InstrData::new("LSR", 3, 6)),
            (0x5E, InstrData::new("LSR", 3, 7)),
            (0x0A, InstrData::new("ASL", 1, 2)),
            (0x06, InstrData::new("ASL", 2, 5)),
            (0x16, InstrData::new("ASL", 2, 6)),
            (0x0E, InstrData::new("ASL", 3, 6)),
            (0x1E, InstrData::new("ASL", 3, 7)),
            (0x58, InstrData::new("CLI", 1, 2)),
            (0x84, InstrData::new("STY", 2, 3)),
            (0x94, InstrData::new("STY", 2, 4)),
            (0x8C, InstrData::new("STY", 3, 4)),
            (0x2A, InstrData::new("ROL", 1, 2)),
            (0x26, InstrData::new("ROL", 2, 5)),
            (0x36, InstrData::new("ROL", 2, 6)),
            (0x2E, InstrData::new("ROL", 3, 6)),
            (0x3E, InstrData::new("ROL", 3, 7)),
            (0x6A, InstrData::new("ROR", 1, 2)),
            (0x66, InstrData::new("ROR", 2, 5)),
            (0x76, InstrData::new("ROR", 2, 6)),
            (0x6E, InstrData::new("ROR", 3, 6)),
            (0x7E, InstrData::new("ROR", 3, 7)),
            (0xE6, InstrData::new("INC", 2, 5)),
            (0xF6, InstrData::new("INC", 2, 6)),
            (0xEE, InstrData::new("INC", 3, 6)),
            (0xFE, InstrData::new("INC", 3, 7)),
            (0xC6, InstrData::new("DEC", 2, 5)),
            (0xD6, InstrData::new("DEC", 2, 6)),
            (0xCE, InstrData::new("DEC", 3, 6)),
            (0xDE, InstrData::new("DEC", 3, 7)),
            //here be unofficial ops.
            (0x1A, InstrData::new("*NOP", 1, 2)),
            (0x3A, InstrData::new("*NOP", 1, 2)),
            (0x5A, InstrData::new("*NOP", 1, 2)),
            (0x7A, InstrData::new("*NOP", 1, 2)),
            (0xDA, InstrData::new("*NOP", 1, 2)),
            (0xFA, InstrData::new("*NOP", 1, 2)),
            (0x80, InstrData::new("*NOP", 2, 2)),
            (0x82, InstrData::new("*NOP", 2, 2)),
            (0x89, InstrData::new("*NOP", 2, 2)),
            (0xC2, InstrData::new("*NOP", 2, 2)),
            (0xE2, InstrData::new("*NOP", 2, 2)),
            (0x04, InstrData::new("*NOP", 2, 3)),
            (0x44, InstrData::new("*NOP", 2, 3)),
            (0x64, InstrData::new("*NOP", 2, 3)),
            (0x14, InstrData::new("*NOP", 2, 4)),
            (0x34, InstrData::new("*NOP", 2, 4)),
            (0x54, InstrData::new("*NOP", 2, 4)),
            (0x74, InstrData::new("*NOP", 2, 4)),
            (0xD4, InstrData::new("*NOP", 2, 4)),
            (0xF4, InstrData::new("*NOP", 2, 4)),
            (0x0C, InstrData::new("*NOP", 3, 4)),
            (0x1C, InstrData::new("*NOP", 3, 4)),
            (0x3C, InstrData::new("*NOP", 3, 4)),
            (0x5C, InstrData::new("*NOP", 3, 4)),
            (0x7C, InstrData::new("*NOP", 3, 4)),
            (0xDC, InstrData::new("*NOP", 3, 4)),
            (0xFC, InstrData::new("*NOP", 3, 4)),
            (0xA7, InstrData::new("*LAX", 2, 3)),
            (0xB7, InstrData::new("*LAX", 2, 4)),
            (0xAF, InstrData::new("*LAX", 3, 4)),
            (0xBF, InstrData::new("*LAX", 3, 4)),
            (0xA3, InstrData::new("*LAX", 2, 6)),
            (0xB3, InstrData::new("*LAX", 2, 5)),
            (0x87, InstrData::new("*SAX", 2, 3)),
            (0x97, InstrData::new("*SAX", 2, 4)),
            (0x8F, InstrData::new("*SAX", 3, 4)),
            (0x83, InstrData::new("*SAX", 2, 6)),
            (0xEB, InstrData::new("*SBC", 2, 2)),
            (0xC7, InstrData::new("*DCP", 2, 5)),
            (0xD7, InstrData::new("*DCP", 2, 6)),
            (0xCF, InstrData::new("*DCP", 3, 6)),
            (0xDF, InstrData::new("*DCP", 3, 7)),
            (0xDB, InstrData::new("*DCP", 3, 7)),
            (0xC3, InstrData::new("*DCP", 2, 8)),
            (0xD3, InstrData::new("*DCP", 2, 8)),
            (0xE7, InstrData::new("*ISB", 2, 5)),
            (0xF7, InstrData::new("*ISB", 2, 6)),
            (0xEF, InstrData::new("*ISB", 3, 6)),
            (0xFF, InstrData::new("*ISB", 3, 7)),
            (0xFB, InstrData::new("*ISB", 3, 7)),
            (0xE3, InstrData::new("*ISB", 2, 8)),
            (0xF3, InstrData::new("*ISB", 2, 4)),
            (0x07, InstrData::new("*SLO", 2, 5)),
            (0x17, InstrData::new("*SLO", 2, 6)),
            (0x0F, InstrData::new("*SLO", 3, 6)),
            (0x1F, InstrData::new("*SLO", 3, 7)),
            (0x1B, InstrData::new("*SLO", 3, 7)),
            (0x03, InstrData::new("*SLO", 2, 8)),
            (0x13, InstrData::new("*SLO", 2, 8)),
            (0x27, InstrData::new("*RLA", 2, 5)),
            (0x37, InstrData::new("*RLA", 2, 6)),
            (0x2F, InstrData::new("*RLA", 3, 6)),
            (0x3F, InstrData::new("*RLA", 3, 7)),
            (0x3B, InstrData::new("*RLA", 3, 7)),
            (0x23, InstrData::new("*RLA", 2, 8)),
            (0x33, InstrData::new("*RLA", 2, 8)),
            (0x47, InstrData::new("*SRE", 2, 5)),
            (0x57, InstrData::new("*SRE", 2, 6)),
            (0x4F, InstrData::new("*SRE", 3, 6)),
            (0x5F, InstrData::new("*SRE", 3, 7)),
            (0x5B, InstrData::new("*SRE", 3, 7)),
            (0x43, InstrData::new("*SRE", 2, 8)),
            (0x53, InstrData::new("*SRE", 2, 8)),
            (0x67, InstrData::new("*RRA", 2, 5)),
            (0x77, InstrData::new("*RRA", 2, 6)),
            (0x6F, InstrData::new("*RRA", 3, 6)),
            (0x7F, InstrData::new("*RRA", 3, 7)),
            (0x7B, InstrData::new("*RRA", 3, 7)),
            (0x63, InstrData::new("*RRA", 2, 8)),
            (0x73, InstrData::new("*RRA", 2, 8)),
        ]);

        Instr { instrs: map }
    }
}
